fragment DialogParts on DialogModel {
    id
    visitor {
      id
    }
    # TODO Переназвать $limit -> $messagesLimit
    messages(orderBy: $orderBy, limit: $limit) {
    ... MessagesParts
    }
}